### PR TITLE
Adding `nodejs-sveltekt` example

### PR DESCRIPTION
**Pull request by wayneshn**
This pull request contributes three new examples to the `ob-example` repository: `oceanbase-python-api`, `oceanbase-sequelize`, and `oceanbase-sveltekit`. These examples are intended to demonstrate the use of OceanBase with different languages and frameworks.

## Example Description

The `oceanbase-python-api` example illustrates how Python developers can interact with OceanBase, the `oceanbase-sequelize` example demonstrates how to use OceanBase with Sequelize as the ORM, and the `oceanbase-sveltekit` example showcases the integration of OceanBase with the Sveltekit framework. 

## Other Information

The `.gitignore` file has been updated to ignore files and directories typically found in Python and Node projects, such as `node_modules`, `.env`, and other log and cache files.

### CODE REVIEW

**Comment by akaError** [comment]
hi, wayneshn, I just simplify review your commit, greate and detail, but something I want to confirm. Take a example, in oceanbase-sequalize/README.md, u recommend user to spin up a oceanbase cluster, may be in ec2, have u try to use Gitpod platform? and one more thing , can we just run all three project u contributed decently in Gitpod platform and user do not need to set up other environment?

**Comment by wayneshn** [comment]
Hi @whhe Thanks for your comment. I have changed the file name of the projects and pushed only the SvelteKit project in this PR, the new project folder is called nodejs-sveltekt.

**Comment by wayneshn** [comment]
> hi, wayneshn, I just simplify review your commit, greate and detail, but something I want to confirm. Take a example, in oceanbase-sequalize/README.md, u recommend user to spin up a oceanbase cluster, may be in ec2, have u try to use Gitpod platform? and one more thing , can we just run all three project u contributed dependently in Gitpod platform and user do not need to set up other environment?

Hi thanks for your comment. I'm sure GitPod would be an elegant way to do the deployment. But I have always been running OB on an EC2 instance without a problem and I don't use GitPod. Thanks!

**Comment by whhe** [comment]
Thanks for the update, and sorry that you may need to modify the directory a little more, as I recently made some changes on the repo structure in https://github.com/oceanbase/ob-example/pull/21, now you may need to move your project to the `examples/application` or another suitable directory, and add the corresponding introduction to the readme in the [examples](https://github.com/oceanbase/ob-example#examples) section. 

For Gitpod, we recommend users to deploy a standalone OceanBase and try our example projects on it, so it's required to test the example project and make sure it can be executed directly on Gitpod.

**Comment by wayneshn** [comment]
OK I'll make changes

**Comment by whhe** [comment]
Hi @wayneshn, any update for this PR?

**Comment by whhe** [comment]
Prepare for subsequent refactoring, merging.

**Pull request merged**
